#!/bin/bash
# Re-runs every Phase 1 verification (offline, 0 tokens) and prints a markdown execution log.
C="$(dirname "$0")/capture.sh"; P=".venv/bin/python"
T="PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 $P -m pytest -q -p no:warnings"          # summary line only
V="PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 $P -m pytest -v -p no:warnings"          # one line per test
F="| grep -E 'PASSED|FAILED|passed|failed' | sed -E 's/^tests\/[^:]+:://; s/ +\[ *[0-9]+%\]//'"
echo; echo "---"; echo; echo "## 7. Execution log — Phase 1 (commands and real output)"; echo
echo "Every block below was run on $(date '+%Y-%m-%d') in \`bhargava-code/\`, offline (0 API tokens). Output is pasted unedited. Re-generate with \`tools/phase1_execlog.sh\`."
echo; echo "### Step 0.3 — Branch and baseline"
$C "Confirm master is the latest from GitHub" "git fetch --all --prune && git rev-parse --short origin/master"
$C "Work branch and commits" "git log --oneline -3 && git branch --show-current"
$C "Files changed in Phase 1" "git diff --stat ae77fb4..f56b651"
echo; echo "### Before Phase 1 — the 5 failing cases (from Bhargava's committed after-run)"
$C "Read failing cases from results/after_react.json" "$P -c \"import json;[print(f\\\"{r['case']:<28} pass={r['passed']}  ms={r['outcomes'][0]['ms']:>7}  {(r['outcomes'][0].get('error') or '; '.join(r['outcomes'][0]['fails']))[:90]}\\\") for r in json.load(open('results/after_react.json')) if not r['passed']]\""
echo; echo "### Step 1.1 — Confirmation flow"
$C "Code: ReAct now dispatches through the policy layer" "grep -n 'policy.guarded_run' ami/planner.py"
$C "Code: policy passes scope and confirmed to the tool" "grep -n 'scope = args.pop\|args\[\"confirmed\"\] = True\|tools.run(name, args, scope=scope)' ami/policy.py"
$C "Tests: confirmation gate" "$V tests/test_policy.py::TestGuardedRunConfirmation 2>&1 $F"
$C "Tests: ReAct cancel across turns" "$V tests/test_planner.py -k 'two_turns or same_turn' 2>&1 $F"
$C "Dry-run of the real eval case with a scripted model (script: tools/dryrun_eval.py)" "$P ../tools/dryrun_eval.py"
echo; echo "### Step 1.2 — Eligibility before confirmation"
$C "Code: shared eligibility rules used by tools and policy" "grep -n 'def eligibility\|eligibility(' ami/tools.py ami/policy.py"
$C "Tests: refused before confirmation" "$V tests/test_policy.py::TestRefusedBeforeConfirmation 2>&1 $F"
echo; echo "### Step 1.3 — Fail fast on model / gateway errors"
$C "Code: SDK retries off, timeout, retry budget" "grep -n 'max_retries\|timeout=\|deadline' ami/llm.py; grep -n 'LLM_RETRY_MAX_SECONDS\|LLM_TIMEOUT_SECONDS' ami/config.py"
$C "Tests: retry budget and degraded reply" "$V tests/test_llm_retry.py tests/test_planner.py -k 'retry or budget or degrades' 2>&1 $F"
echo; echo "### Step 1.4 — Notes and long-term context reach the model"
$C "Code: react sends extra + long-term context; web passes them" "grep -n 'longterm=None\|filter(None, \[work.brief(), extra\])' ami/planner.py; grep -n 'extra=note, longterm=LONGTERM\|context=ltm' web.py"
$C "Code: web scrubs input BEFORE adding it to memory (check_input line < add_user line)" "grep -n 'text, note = policy.check_input(text)\|convo.add_user(text)' web.py"
$C "Code: web uses the same system prompt the evals measure" "grep -n '^SYSTEM =' web.py"
$C "Tests: note reaches the model; preview not recorded" "$V tests/test_planner.py tests/test_memory.py -k 'policy_note or preview_is_not' 2>&1 $F"
echo; echo "### Step 1.5 — Eval harness login"
$C "Who the eval logs in as for 'find by email' (before Phase 1: demo1@cofy.ai)" "$P -c \"import warnings;warnings.filterwarnings('ignore');import evals;from ami import store;c=next(x for x in evals.CASES if x['name']=='find by email');print('scope ->', evals._scope_for(c, store))\""
echo; echo "### Step 1.6 — Full test suite, before vs after"
$C "Before Phase 1 (master ae77fb4)" "git switch -q --detach ae77fb4 && $T 2>&1 | tail -1; git switch -q fix/s1-and-eval-failures"
$C "After Phase 1 (branch fix/s1-and-eval-failures)" "$T 2>&1 | tail -1"
